ganglia/urls.py
from django.conf.urls import patterns, url
from ganglia import views

urlpatterns = patterns('',
	url(r'^$',views.index,name='index'),
	url(r'^(?P<resource_id>\d+)/$', views.detail, name='detail'),
    url(r'^xml/(?P<host_name>\S+)/(?P<rrd_name>\w+)/(?P<time_slot>\d+)/$', views.get_text)
)

monitor/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'monitor.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^ganglia/', include('ganglia.urls',namespace="ganglia")),
    url(r'^admin/', include(admin.site.urls)),
)

ganglia/models.py
from django.db import models

# Create your models here.
class Host(models.Model):
	host_name = models.CharField(max_length=200)
	host_ip = models.CharField(max_length=200)
	def __unicode__(self):
		return self.host_name

class Resource(models.Model):
	host = models.ForeignKey(Host)
	res_hostname = models.CharField(max_length=200)
	res_related = models.TextField(default="")
	res_name = models.CharField(max_length=200)
	res_type = models.CharField(max_length=200)
	def __unicode__(self):
		return self.res_name

class Metric(models.Model):
	resource = models.ForeignKey(Resource)
	metric_name = models.CharField(max_length=200)
	mtr_hostname = models.CharField(max_length=200)
	def __unicode__(self):
		return self.metric_name


	
	

ganglia/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from ganglia.models import Resource,Metric,Host
import jpype
import json
from ganglia.util import get_relate,str_to_list,res_img,read_ganglia_conf,add_items,reason_func
import os 
import commands 
from sys import stdin,stdout,stderr


# Create your views here.
def index(request):
    #add content to database
    hname_list = read_ganglia_conf()
    add_items(hname_list)
    #get content from table
    host_list = Host.objects.all()
    resource_list = Resource.objects.all()
#    get_relate(resource_list)
    context = {'resource_list': resource_list,'host_list':host_list}
    return render(request,'ganglia/index.html',context)


def detail(request,resource_id):
    res = get_object_or_404(Resource,pk=resource_id)
    metric_list = Metric.objects.filter(resource=res)

    #generate graph for every metric
    path_list = res_img(metric_list)

    mtc_list = []
    for metric in metric_list:
        mtc= {}
        mtc["mtc_name"] = metric.metric_name
        mtc['img_path'] = path_list[metric.metric_name]
        mtc_list.append(mtc)
    
    rel_namelist = reason_func(res.res_name)
    print rel_namelist
    rel_list = []
    for rel_name in rel_namelist:
        """attention after filter you get a list"""
        rel_fil = Resource.objects.filter(res_name=rel_name.strip(),res_hostname=res.res_hostname)
        if not len(rel_fil)==0:
            rel_list.append(rel_fil[0])
    return render(request,"ganglia/detail.html",{'resource':res,'metric_list':mtc_list,'relate_list':rel_list})


'''
considering there is one and only one specified cluster
this function generated the according xml of the rrd
'''
def get_text(request, host_name, rrd_name, time_slot):
    base_url = "/var/lib/ganglia/rrds/my_cluster/"
    rrd_path = base_url + host_name + "/" + rrd_name + ".rrd"

    end = "now"    
    if time_slot == "1": 
        start = "end-1h"
        step = "60"
    elif time_slot == "2":
        start = "end-1d"
        step = "960"
    elif time_slot == "3":
        start = "end-1w"
        step = "7200"
    elif time_slot == "4":
        start = "end-1m"
        step = "7200"
    else:        
        start = "end-600"
        step = "60"
    command = "rrdtool xport --start %s --end %s DEF:ds=%s:sum:AVERAGE:step=%s XPORT:ds:legend" % (start,end,rrd_path,step)
    status,output = commands.getstatusoutput(command)
    return HttpResponse(output)

ganglia/templates/ganglia/base.html
<html lang="en">
<head>
    {% load staticfiles%}
    <link rel="stylesheet" href="{% static 'ganglia/css/bootstrap.min.css' %}" />
    <link href="{% static 'ganglia/css/examples.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'ganglia/js/jquery.min.js' %}"></script>
    <script src="{% static 'ganglia/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'ganglia/js/jquery.flot.min.js' %}"></script>
    <script src="{% static 'ganglia/js/jquery.flot.autoMarkings.js' %}"></script>
    <script src="{% static 'ganglia/js/jquery.flot.time.js' %}"></script>
</head>

<body>
    {% block title %}{% endblock %}
    {% block content %}{% endblock %}
</body>
<footer align=center style="bottom:0">
	Ontology-Monitoring--Copyright cshuo; 2015-3-1
</footer>
</html>

ganglia/templates/ganglia/detail.html
{% extends "ganglia/base.html" %}

{% block title %} 
<div class="row" style="background-color:#2e2e2e;padding:15px;color:#a6a6a6">
	<div class="col-md-6 col-md-offset-3">
		<h2 align=center>
			Resource: {{ resource.res_name }}
			<small>({{resource.res_hostname}})</small>
		</h2>
	</div>
	<div class="col-md-1 col-md-offset-1" style="padding-top:20px">
		<a href="{% url 'ganglia:index' %}" style="font-size:20px;color:#a6a6a0">Home</a>
	</div>
</div>
<div id="test"></div>
<br/>
{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-2 col-xs-offset-1">
      <br/>
      <h4>Metric List</h4>
      <ul class="nav nav-pills nav-stacked">
        {% for metric in metric_list %}
        <li role="presentation">
         <a href="#" onclick="click_choose('{{metric.mtc_name}}')">{{metric.mtc_name}}</a>
       </li>
       {% endfor %}
     </ul>			
     <br/>
     <label>
      <input id="enableAlert" type="checkbox"></input>	
      <span style="padding:3px;font-size:15px">Enable Alerting</span>
    </label>
    <br/><br/>  		
    <div id="alert-content" style="display:none">				
      <p>Alert on:
       <select id="selector"></select>
     </p>		
     <p>Threshold: <span id="unit"></span></p> 			
     <p>upper bound:
       <input id="upper_bd" type="text" style="text-align: right; width:5em" /> 			
     </p>			  			  			
     <p>lower bound:
       <input id="lower_bd" type="text" style="text-align: right; width:5em" /> 			
     </p>				
     <button type="button" id="check_button" class="btn btn-primary">
      submitting
    </button>
  </div>      
  <div id="alert-content-setted" style="display:none">      
    <p>Alert on: <span id="alert-name"></span></p>
    <p>upper-bound: <span id="upper-setted"></span></p>
    <p>lower-bound: <span id="lower-setted"></span></p>        
  </div>
</div>

<div class="col-md-8">
 <div id="middle_container" align="center" class="row">
  {% for metric in metric_list %}
  {% if forloop.counter == 1 %}
  <div id={{ metric.mtc_name }} style="display:block">
   {% else %}
   <div id={{ metric.mtc_name }} style="display:none">
    {% endif %}
    <div align="center" class="row">
     <button onclick="button_plot('{{ metric.mtc_name}}/1/',this)" class="btn btn-primary">last hour</button> 
     <button onclick="button_plot('{{ metric.mtc_name}}/2/',this)" class="btn btn-primary">last day</button> 
     <button onclick="button_plot('{{ metric.mtc_name}}/3/',this)" class="btn btn-primary">last week</button> 
     <button onclick="button_plot('{{ metric.mtc_name}}/4/',this)" class="btn btn-primary">last month</button> 
   </div>
   <div id="graph_container" class="demo-container">
     <div id="graph_holder1" class="demo-placeholder" style="display:block"></div>
     <div id="graph_holder2" class="demo-placeholder" style="display:none"></div>
     <div id="graph_holder3" class="demo-placeholder" style="display:none"></div>
     <div id="graph_holder4" class="demo-placeholder" style="display:none"></div>
   </div>
 </div>
 {% endfor %}
</div>
</div>
</div>
</div>

<div class="modal fade" id="alert_modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">  
    <div class="modal-content">
      <div class="modal-header">        
        <h4 class="modal-title" align="center">Warning</h4>
      </div>
      <div class="modal-body">
       <div class="alert alert-danger" role="alert">
         <p><span id="warn-mtc"></span> have been exceeding the threshold in last 10 minutes</p>         
       </div>      
       {% if relate_list %}
       <h4 align="center">Suggested metering list: </h4>
       <ul style="padding-left:60px">
        {% for res in relate_list %}
        <li><a href="{% url 'ganglia:detail' res.id %}">{{res.res_name}}</a></li>
        {% endfor %}
      </ul>
      {% else %}
      <h5> Maybe this is the cause of the problem... </h5>
      {% endif %}     
    </div>     
  </div>
</div>
</div>



<script type="text/javascript">

var plot_list = {}; //global plot obj intend for realize realtime update
var update_index;
var update_name;
var init_alert = 1;

{% for g_mtc in metric_list %}
var plot_1,plot_2,plot_3,plot_4;
plot_list['{{ g_mtc.mtc_name}}'] = [plot_1,plot_2,plot_3,plot_4];
{% if forloop.counter == 1 %}
update_name = '{{ g_mtc.mtc_name }}';
update_index = 0;
{% endif %}
{% endfor %}


$('#check_button').on('click', function () {    
  if(document.getElementById('upper_bd').value.length == 0 
    || document.getElementById('lower_bd').value.length == 0){
    alert("please input!!");
}  
else{    
  var s = document.getElementById("selector");    
  var alert_name = s.options[s.selectedIndex].text;
  $("#alert-content").hide();
  $("#alert-name").html(alert_name+" "+get_unit('{{ resource.res_name }}'));
  $("#upper-setted").html($("#upper_bd").val());
  $("#lower-setted").html($("#lower_bd").val());
  $("#alert-content-setted").fadeIn();        
  if(init_alert == 1){        
    setInterval(alert_func,3000);    
    init_alert = 0;
  }
}
});

//write unit of the threshold according to res name of the page
$("#unit").html(get_unit('{{ resource.res_name }}'));


//click checkbox to control the display of alert-content
$('#enableAlert').on('change', function() {     
  if (this.checked) {
    $('#alert-content').fadeIn();
  }
  else{
   $('#alert-content').fadeOut();
   $('#alert-content-setted').fadeOut();
 }
});


//init the pulldown content
$(function(){
	var sel = document.getElementById("selector");
	var all_elem = document.createElement("option");
	all_elem.innerHTML = "all_together";
	sel.appendChild(all_elem);
	{% for pulldown_mtc in metric_list %}
	var e = document.createElement("option");
	e.innerHTML = '{{ pulldown_mtc.mtc_name }}';
	sel.appendChild(e);
	{% endfor %}
});

//init plotting when first load the page
$(function(){
	var elem;
	var init_url;
	{% for metric in metric_list %}
	{% if forloop.counter == 1 %}
	elem = document.getElementById('{{ metric.mtc_name}}');
	init_url = "http://localhost:8000/ganglia/xml/" + '{{ resource.res_hostname}}/{{ metric.mtc_name}}/1/';
	{% endif%}
	{% endfor%}
	gra_elem = elem.querySelector("#graph_container").querySelector("#graph_holder1");
	plot_g(init_url,gra_elem,'1');
});


setInterval(update_plot,30000);

//check alerting every 3 minutes
// setInterval(check_alert,2000);  

function click_choose(text){
	{% for metric in metric_list %}      
	if('{{ metric.mtc_name }}' == text){
		document.getElementById('{{ metric.mtc_name }}').style.display='block';
		item_plot(text);
	}
	else
		document.getElementById('{{ metric.mtc_name }}').style.display='none';
	{% endfor %}
}

/**
  funtion for plotting
  */
  function plot_g(url,obj,type){
  	var time_fmt;
  	var op;
  	var update_interval = 30000;
  	var plot_index;
  	var mtc_name = obj.parentNode.parentNode.id;

  	if(type == '1'){
  		time_fmt = "%H:%M";
  		plot_index = 0;
  		op = {
  			hour: "2-digit", minute: "2-digit"
  		};
  	}
  	else if(type == '2'){
  		time_fmt = "%y/%m/%d %H:%M";
  		plot_index = 1;
  		op = {
  			month: "short",day: "numeric", hour: "2-digit", minute: "2-digit"
  		};
  	}
  	else if(type == '3'){
  		time_fmt = "%y/%m/%d";
  		plot_index = 2;
  		op = {
  			month: "short",day: "numeric"
  		};
  	}
  	else{
  		time_fmt = "%y/%m/%d";
  		plot_index = 3;
  		op = {
  			month: "short",day: "numeric"
  		};
  	}

  	var value_ary = get_xml(url);
  	if(value_ary.length > 0){
  		plot_list[mtc_name][plot_index]= $.plot(obj,
  			[{data:value_ary,label: obj.parentNode.parentNode.id + get_unit('{{ resource.res_name }}')}],					
  			{
  				xaxis: {
  					mode: "time",
  					timezone: "browser",
  					timeformat: time_fmt
  				},
  				series: {
  					lines: {
  						show: true,
              fill: true
  					},            
  					points: {
  						show: false
  					}  					
  				},
  				grid: {
  					hoverable: true,
  					clickable: true 
  				},
  				legend:{
  					position:"nw"
  				}
  			});

  		$("<div id='tooltip'></div>").css({
  			position: "absolute",
  			display: "none",
  			border: "1px solid #faa",
  			"border-radius": "5px",
  			padding: "3px",
  			"background-color": "#fee",
  			opacity: 0.90
  		}).appendTo("body");

  		$(obj).bind("plothover", function (event, pos, item) {
  			if (item) {
  				var x = item.datapoint[0]/1000 + 8*3600,
  				y = item.datapoint[1].toFixed(2);
  				var t = new Date(1970,0,1);
  				t.setSeconds(x);
  				$("#tooltip").html(t.toLocaleDateString("en-US",op)+"<br/>"+"value: "+y).
  				css({top: item.pageY+5, left: item.pageX+5}).
  				fadeIn(150);
  			} else {
  				$("#tooltip").hide();
  			}
  		});

  	}
  	else{
  		obj.innerHTML = "failed to get msg!!";
  	}
  }



/**
  get unit
  **/
  function get_unit(axes_name){
  	var unit = "";
  	if(axes_name == "Mem")
  		unit = "(KB)";
  	else if(axes_name == "Disk")
  		unit = "(GB)";
  	else if(axes_name == "Cpu")
  		unit = "(%)";
  	else if(axes_name == "Network")
  		unit = "(packet/s)";
  	return unit;
  }

/**
  function to update in specific time interval
  **/
  function update_plot(){
  	var base_url  = "http://localhost:8000/ganglia/xml/" + '{{ resource.res_hostname}}/'+update_name +'/';
  	var url_list = [];
  	url_list.push(base_url + '1/');
  	url_list.push(base_url + '2/');
  	url_list.push(base_url + '3/');
  	url_list.push(base_url + '4/');	
  	var plot_upd = plot_list[update_name][update_index];
  	plot_upd.setData([{data:get_xml(url_list[update_index]),label:update_name+get_unit('{{ resource.res_name}}')}]);
  	plot_upd.setupGrid();
  	plot_upd.draw();	
  }



/**
  function for getting xml data from rrd
  **/
  function get_xml(req_url){
  	var v_array = [];
  	var xml_http = new XMLHttpRequest();
  	xml_http.open("GET",req_url,false);
  	xml_http.send();
  	if(xml_http.readyState==4 && xml_http.status==200){
  		xmlDoc = jQuery.parseXML(xml_http.responseText);
  		$(xmlDoc).find('row').each(function(){
  			var time = parseFloat($(this).children('t').text());
  			var value = parseFloat($(this).children('v').text());
				v_array.push([time*1000,value]);      //time series xaxis require x to be millis
			});
  	}
  	return v_array;
  }

/**
  plot according to the button clicked
  */
  function button_plot(url,obj){
  	var base_url;
  	var child_node;
  	var graph_obj;
  	var time_type;
  	time_type = url.charAt(url.length-2);
  	switch (time_type){
  		case '1': 
  		update_index = 0;
  		break;
  		case '2':
  		update_index = 1;
  		break;
  		case '3':
  		update_index = 2;
  		break;
  		case '4':
  		update_index = 3;
  		break;
  		default:
  		alert("error index");
  		break;
  	}

  	base_url = "http://localhost:8000/ganglia/xml/" + '{{ resource.res_hostname}}/' + url;
	//get child by id 
	graph_id = "#graph_holder"+time_type;
	graph_obj = obj.parentNode.parentNode.querySelector("#graph_container").querySelector(graph_id);
	child_node = graph_obj.parentNode.children;
	for(var i=0;i<child_node.length;i++)
		child_node[i].style.display = 'none';
	graph_obj.style.display = 'block';
	plot_g(base_url,graph_obj,time_type);
}

/**
  plot according list item clicked 
  **/
  function item_plot(m_name){
  	var elem_plot;
  	var url_item = [];
  	update_name = m_name;
  	update_index = 0;

  	url_item = "http://localhost:8000/ganglia/xml/" + '{{ resource.res_hostname}}/' + m_name + "/1/";
  	elem_plot= document.getElementById(m_name).querySelector("#graph_container").querySelector("#graph_holder1");
  	plot_g(url_item,elem_plot,'1');
  }


/**
  function to check whether the specified metric exceed the threshold 
  **/
  function alert_func(){    
    var base_url = "http://localhost:8000/ganglia/xml/" + '{{ resource.res_hostname}}/';
    var s = document.getElementById("selector");    
    var alert_mtc = s.options[s.selectedIndex].text;
    var upper_bound = $("#upper_bd").val();
    var lower_bound = $("#lower_bd").val();    
    var m_value = [];
    var alert_sign = 1;
    var all_NaN = 1;  

    //checkbox is not checked, return directly
    if(!$('#enableAlert').is(':checked'))
      return;  

    if(alert_mtc == "all_together"){   //all metric of the resource together              
      var all_mtc_array = [];      
      {% for m in metric_list %}        //get all metric xml data in last 10 minutes
      var m_url = base_url + '{{ m.mtc_name }}/5/';
      var m_data = get_xml(m_url);
      all_mtc_array.push(m_data);
      {% endfor %}      
      
      for(var i=0;i<all_mtc_array[0].length;i++){
        m_value.push(all_mtc_array[0][i][1]);
      }
      for(var i=1;i<all_mtc_array.length;i++){
        for(var j=0;j<m_value.length;j++){          
          m_value[j] += all_mtc_array[i][j][1];
        }            
      }
    }
    else{           //only one metric of the resource in the page
      var alert_url = base_url + alert_mtc + "/5/";
      var xml_data = get_xml(alert_url);            
      for (var i=0;i<xml_data.length;i++){
        m_value.push(xml_data[i][1])      
      }      
    }

    //judge whether all value is within the threshold
    for(var i=0;i<m_value.length;i++){      
      if(!isNaN(m_value[i])){
        all_NaN = 0;
        if(m_value[i]<upper_bound && m_value[i]>lower_bound){
          alert_sign = 0;
        }      
      }      
    }

    if(all_NaN ==1 )
      alert("all Num is NaN!!");    
    else if(alert_sign ==1){
      $("#warn-mtc").html(alert_mtc);
      $("#alert_modal").modal("show");      
    }            
  }//end of func

</script>

{% endblock %}

ganglia/templates/ganglia/index.html
{% extends "ganglia/base.html" %}
{% block title%}
<div class="row" style="background-color:#2e2e2e;padding:15px;color:#a6a6a6">
	<div class="col-md-6 col-md-offset-3">
		<div> 
			<h1 align=center>
				Cluster Monitor
			</h1>
		</div>
	</div>
	<div class="col-md-1 col-md-offset-1" style="padding-top:20px">
		<a href="#" style="font-size:20px;color:#a6a6a0">About</a>
	</div>
</div>
{% endblock %}

{% block content %}
{% load staticfiles %}
<div class="container-fluid"> 
	<div class="row">
		<div id="blank" class="col-md-4"></div>
		<div id="host_div" class="col-md-4">
			<h3 align=center>Hosts in cluster</h3>
			{% if host_list and resource_list %}
			<div class="container-fluid">
				<div class="row">
					{% for host in host_list %}
						<div class="col-md-4">
							<a onclick="show_res(this,'{{ host.host_name }}')">
								<img src="{% static 'ganglia/images/pc.png' %}" height="60" width="60"></img>
								<h4>{{ host.host_name}}</h4>
							</a>
						</div>
					{% endfor%}
				</div>
			</div>
			{% else %}
				<h3 align=center>No Host</h3>
			{% endif %}
		</div>
		<div id="res_div" class="col-md-3 col-md-offset-1" style="display:none">
			world
		</div>
	</div>
	<!--div class="footer navbar-fixed-bottom" align=center style="background-color:#2e2e2e;padding:25px"-->
</div>

<script type="text/javascript">
function get_data(){
	var texthttp;
	texthttp = new XMLHttpRequest();
	texthttp.onreadystatechange=function(){                
		if(texthttp.readyState==4 && texthttp.status==200){
			document.getElementById("myDiv").innerHTML = texthttp.responseText;
		}
		else{
			document.getElementById("myDiv").innerHTML = "failed to get msg!!";
		}
	}
	texthttp.open("GET","http://localhost:8000/ganglia/xml/localhost/cpu_idle/4/",true);
	texthttp.send();
}


/**
 function for showing the resources in the host clicked
 **/
function show_res(obj,h_name){
	var added_div = document.getElementById("res_div");
	var p_title = document.createElement('h3');
	var hosts_div = document.getElementById("host_div");
	host_div.setAttribute('class',"col-md-4 col-md-offset-2");
	$("#res_div").empty();
	p_title.innerHTML = "Resources in "+ h_name;
	p_title.setAttribute('align',"center");
	added_div.appendChild(p_title);
	{% for resource in resource_list %}
		if(h_name == '{{ resource.res_hostname }}'){
			var res_div = document.createElement("div");
			var res_a = document.createElement("a");
			res_div.setAttribute('class',"alert alert-success");
			res_div.setAttribute('align',"center");
			res_a.setAttribute('href',"{% url 'ganglia:detail' resource.id %}");
			res_a.innerHTML="{{ resource.res_name }}";
			res_div.appendChild(res_a);
			added_div.appendChild(res_div);
		}
	{% endfor %}
	$("#blank").hide();
	$("#res_div").fadeIn();
}

</script>
{% endblock %}

ganglia/templates/ganglia/index_back.html
{% extends "ganglia/base.html" %}
{% block title%}
<div class="row" style="background-color:#2e2e2e;padding:15px;color:#a6a6a6">
	<div class="col-md-6 col-md-offset-3">
		<div> 
			<h1 align=center>
				Monitored Hosts
				<small>resources list</small>
			</h1>
		</div>
	</div>
	<div class="col-md-1 col-md-offset-1" style="padding-top:20px">
		<a href="#" style="font-size:20px;color:#a6a6a0">About</a>
	</div>
</div>
<br/><br/>
{% endblock %}

{% block content %}
{% load staticfiles %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			{% if host_list and resource_list %}
			{% for host in host_list %}
			<div class="alert alert-info">
				<h4 align="center">
					{% load ganglia_tag %}
					<a data-toggle="collapse" href="#{{ host.host_name|repl:"." }}" aria-expanded="false" aria-controls="{{ host.host_name|repl:"." }}">{{ host.host_name}}</a>
				</h4>
			</div>
			<ul id="{{ host.host_name|repl:"." }}" class="collapse list-group">
				{% for resource in resource_list %}
				{% if resource.res_hostname == host.host_name%}
				<li class="list-group-item">
				<a href="{% url 'ganglia:detail' resource.id %}">{{resource.res_name}}</a>
				</li>
				{% endif %}
				{% endfor %}
			</ul>
			{% endfor %}
			{% else %}
			<p>No resource are available</p>
			{% endif %}
		</div>
	</div>
	<!--div class="footer navbar-fixed-bottom" align=center style="background-color:#2e2e2e;padding:25px"-->
	<div class="footer" align=center style="padding-top:65px">
		Ontology-Monitoring--Copyright cshuo; 2015-3-1
	</div>
</div>

<script type="text/javascript">
function get_data(){
	var texthttp;
	texthttp = new XMLHttpRequest();
	texthttp.onreadystatechange=function(){                
		if(texthttp.readyState==4 && texthttp.status==200){
			document.getElementById("myDiv").innerHTML = texthttp.responseText;
		}
		else{
			document.getElementById("myDiv").innerHTML = "failed to get msg!!";
		}
	}
	texthttp.open("GET","http://localhost:8000/ganglia/xml/localhost/cpu_idle/4/",true);
	texthttp.send();
}
</script>
{% endblock %}

ganglia/templates/ganglia/metric_png.html
{% for metric in metric_list %}
<div align="center" class="row">
<div class="well well-sm col-md-9 col-md-offset-1">
<h4 align="center" class="active">{{metric.mtc_name}} graph</h4>
</div>
</div>

<div align="center" class="row">
    <button onclick=xml_func("url") class="btn btn-primary">last hour</button> 
    <button onclick=xml_func("url") class="btn btn-primary">last day</button> 
    <button onclick=xml_func("url") class="btn btn-primary">last week</button> 
    <button onclick=xml_func("url") class="btn btn-primary">last month</button> 
</div>
<div id=>
<br/>
{% endfor %}